apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: m1j4ynotv-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/m1j4ynotv-java-quarkus-gitops